// get list of listening
export const GET_LISTENING_LIST = 'GET_LISTENING_LIST';
export const GET_LISTENING_LIST_SUCCESS = 'GET_LISTENING_LIST_SUCCESS';
export const GET_LISTENING_LIST_FAIL = 'GET_LISTENING_LIST_FAIL';
