// get all letters in alphabet
export const GET_LETTERS_ALPHABET = 'GET_LETTERS_ALPHABET';
export const GET_LETTERS_ALPHABET_SUCCESS = 'GET_LETTERS_ALPHABET_SUCCESS';
export const GET_LETTERS_ALPHABET_FAIL = 'GET_LETTERS_ALPHABET_FAIL';
