// get list of communication
export const GET_COMMUNICATION_LIST = 'GET_COMMUNICATION_LIST';
export const GET_COMMUNICATION_LIST_SUCCESS = 'GET_COMMUNICATION_LIST_SUCCESS';
export const GET_COMMUNICATION_LIST_FAIL = 'GET_COMMUNICATION_LIST_FAIL';
